#!/bin/bash sh

#
# Filename:         deploy-vfio
# Description:      Effortlessly deploy a VFIO setup (PCI passthrough).
# Author(s):        Alex Portell <github.com/portellam>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

# <remarks> Using </remarks>
# <code>
    source vfiolib-tools
# </code>

# <code>
function Main
{
    # <remarks> Gather arguments. </remarks>
    SetScriptDir || return 1

    if [[ $( whoami ) != "root" ]]; then
        echo -e "$_PREFIX_FAIL User is not sudo/root."
        return 1
    fi

    if ! SetOptions $@; then
        GetUsage; return "$?";
    fi

    # <remarks> Exit early. </remarks>
    if "$_EXECUTE_UNINSTALL_SETUP"; then
        ExecuteSetup
        return "$?"
    fi

    ExecuteEssentials || return 1
    ExecuteExtras || return 1

    # <remarks> Main setup </remarks>
    case true in
        "$_PARSE_IOMMU_FROM_FILE" )
            ExecuteParse "FILE" || return 1
            ;;

        "$_PARSE_IOMMU_FROM_INTERNET" )
            ExecuteParse "ONLINE" || return 1
            ;;

        "$_PARSE_IOMMU_FROM_CACHE" | * )
            ExecuteParse "SYSTEM" || return 1
            ;;
    esac

    ExecuteSelection || return 1
    ExecuteSetup
    return "$?"
}
# </code>

Main "$@"
exit "$?"