#!/bin/bash sh

#
# Filename:         vfiolib-calc
# Description:      Calculate answers and values for setups and usage.
# Author(s):        Alex Portell <github.com/portellam>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

# <remarks> Using </remarks>
# <code>
    source vfiolib-usage
# </code>

# <code>
    function GetHugepageByteSize
    {
        local -u _ANSWER="$1"

        case "$_ANSWER" in
            "1G" || "2M" )
                _IS_HUGEPAGES_SIZE_SET=true
                return 0 ;;

            "" )
                return 1 ;;

            * )
                echo -e "Please answer \"2M\" or \"1G\"."
                return 1 ;;
        esac
    }

    function GetHugepageCount
    {
        if ! GetHugepageMinAndMaxSizes \
            || [[ "$1" == "" ]]; then
            return 1
        fi

        if ! [[ "$1" =~ '^[0-9]+$' ]] \
            || ( [[ "$1" -lt "$_HUGEPAGES_MIN_SIZE" ]] \
            && [[ "$1" -gt "$_HUGEPAGES_MAX_SIZE" ]] ); then
            echo -e "Please answer between \"$_HUGEPAGES_MIN_SIZE\" or \"$_HUGEPAGES_MAX_SIZE\"."
            return 1
        fi

        _IS_HUGEPAGES_COUNT_SET=true
        declare -gi _HUGEPAGES_COUNT="$1"
        return 0
    }

    function GetHugepageMinAndMaxSizes
    {
        declare -gi _HUGEPAGES_MAX_SIZE=0
        declare -gi _HUGEPAGES_MAX_SIZE_IN_KBIT=$( cat /proc/meminfo | grep MemTotal | cut -d ":" -f 2 | cut -d "k" -f 1 )
        declare -gi _HUGEPAGES_MIN_SIZE=0
        declare -gi _HUGEPAGES_MIN_SIZE_IN_KBIT=4194304
        declare -gi _HUGEPAGES_SIZE_IN_KBIT=0

        case "$_HUGEPAGES_BYTE_SUFFIX" in
            "2M" )
                _HUGEPAGES_SIZE_IN_KBIT=2048
                _HUGEPAGES_MIN_SIZE=2 ;;

            "1G" )
                _HUGEPAGES_SIZE_IN_KBIT=1048576
                _HUGEPAGES_MIN_SIZE=1 ;;

            * )
                echo -e "$_PREFIX_ERROR Failed to calculate minimum or maximum values for Hugepages."
                return 1 ;;
        esac

        _HUGEPAGES_MAX_SIZE=$(( "$_HUGEPAGES_MAX_SIZE_IN_KBIT" - "$_HUGEPAGES_MIN_SIZE_IN_KBIT" ))
        _HUGEPAGES_MAX_SIZE=$(( "$_HUGEPAGES_MAX_SIZE" / "$_HUGEPAGES_SIZE_IN_KBIT" ))
        return 0
    }
# </code>