#!/bin/bash sh

#
# Filename:         vfiolib-setup
# Description:      Select VFIO setup.
# Author(s):        Alex Portell <github.com/portellam>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

# TODO:
# * fix 'sed' calls
#
#
#

# <remarks> Using </remarks>
# <code>
    source vfiolib-files
    source vfiolib-extras
    source vfiolib-iommu
# </code>

# <params>
    declare -gr _LINE_GRUB_CMDLINE="quiet iommu=1,pt amd_iommu=on intel_iommu=on video=efifb:off,vesafb:off acpi=force apm=power_off rd.driver.pre=vfio-pci pcie_aspm=off kvm.ignore_msrs=1"
# </params>

# <code>
    function ExcludeGivenVGAIOMMUGroup
    {
        if ! [[ $1 =~ '^[0-9]+$' ]]; then
            return 1
        fi

        # <remarks> Parse all IOMMU groups.  </remarks>
        for _KEY in ${!_IOMMU_LIST[@]}; do
            local _DRIVER="${_DRIVER_LIST[$_KEY]}"
            local _HWID="${_HWID_LIST[$_KEY]}"
            local _IOMMU="${_IOMMU_LIST[$_KEY]}"
            local _VGA_VFIOPCI_HAS_IOMMU=false

            for _VGA_VFIOPCI_IOMMU in ${_VGA_VFIOPCI_IOMMU_LIST[@]}; do
                if [[ "$_VGA_VFIOPCI_IOMMU" == "$_IOMMU" ]]; then
                    _VGA_VFIOPCI_HAS_IOMMU=true
                    break
                fi
            done

            # <remarks> Add IOMMU group if it is not in the VGA list or if it does not match the given IOMMU group, and if it is not in the current VFIO list. </remarks>
            if ( ! $_VGA_VFIOPCI_HAS_IOMMU || [[ "$_IOMMU" != "$1" ]] ) && ! [[ "$_VGA_DRIVER_DELIM" =~ *"$_DRIVER"* ]]; then
                _VGA_DRIVER_DELIM+="${_DRIVER}"
            fi

            # <remarks> Add IOMMU group if it is not in the VGA list or if it does not match the given IOMMU group, and if it is not in the current VFIO list. </remarks>
            if ( ! $_VGA_VFIOPCI_HAS_IOMMU || [[ "$_IOMMU" != "$1" ]] ) && ! [[ "$_VGA_HWID_DELIM" =~ *"$_HWID"* ]]; then
                _VGA_HWID_DELIM+="${_HWID}"
            fi

            # <remarks> Append a delimiter, should the current element be not the last element. </remarks>
            if [[ "$_VGA_DRIVER_DELIM" != "" ]] && [[ "$_IOMMU" != "${_IOMMU_LIST[-1]}" ]]; then
                _VGA_DRIVER_DELIM+=","
            fi

            # <remarks> Append a delimiter, should the current element be not the last element. </remarks>
            if [[ "$_VGA_HWID_DELIM" != "" ]] && [[ "$_IOMMU" != "${_IOMMU_LIST[-1]}" ]]; then
                _VGA_HWID_DELIM+=","
            fi
        done

        # <remarks> Validate lists. </remarks>
        if ! [[ "$_VGA_DRIVER_DELIM" != "$1" ]] || ! [[ "$_VGA_HWID_DELIM" != "$1" ]]; then
            return 1
        fi

        return 0
    }

    function ExecuteMultibootSetup
    {
        if ! "$_HAS_EXECUTED_BACKUPS" \
            || ! GetParamsForSetup \
            || ! SetParamsForMultibootSetup \
            || ! WriteFilesForMultibootSetup \
            || ! ExecuteUpdateAfterSetup; then
            echo -e "$_PREFIX_ERROR Multiboot setup has failed."
            return 1
        fi

        return 0
    }

    function ExecuteStaticSetup
    {
        local -r _PRINT_FAIL="An error occurred: Static setup has failed."

        if "$_EXECUTE_GRUB_STATIC_SETUP" \
            && ( ! "$_HAS_EXECUTED_BACKUPS" \
            || ! GetParamsForSetup \
            || ! SetParamsForGRUBStaticSetup \
            || ! WriteFilesForGRUBStaticSetup \
            || ! ExecuteUpdateAfterSetup ); then
            echo -e "$_PRINT_FAIL"
            return 1
        fi

        if ! "$_EXECUTE_GRUB_STATIC_SETUP" \
            && ( ! "$_HAS_EXECUTED_BACKUPS" \
            || ! GetParamsForSetup \
            || ! SetParamsForNoGRUBStaticSetup \
            || ! WriteFilesForNoGRUBStaticSetup \
            || ! ExecuteUpdateAfterSetup ); then
            echo -e "$_PRINT_FAIL"
            return 1
        fi

        return 0
    }

    function ExecuteUninstallSetup
    {
        if ! "$_HAS_EXECUTED_BACKUPS" \
            || ! ExecuteUpdateAfterSetup; then
            echo -e "$_PREFIX_ERROR Uninstall has failed."
        fi

        return 0
    }

    function ExecuteUpdateAfterSetup
    {
        if ! sudo update-grub \
            || ! sudo update-initramfs -u -k all; then
            echo -e "$_PREFIX_ERROR Failed to update system configuration."
            return 1
        fi

        return 0
    }

    function GetParamsForSetup
    {
        if [[ "${_VFIOPCI_DRIVER_LIST[@]}" -eq 0 ]] \
            || ( [[ "${_VFIOPCI_HWID_LIST[@]}" -eq 0 ]] \
                && [[ "${_PCISTUB_HWID_LIST[@]}" -eq 0 ]] \
                && [[ "${_VGA_VFIOPCI_DRIVER_LIST[@]}" -eq 0 ]] \
                && [[ "${_VGA_VFIOPCI_HWID_LIST[@]}" -eq 0 ]] ); then
            echo -e "$_PREFIX_ERROR Required parsed IOMMU group lists are empty."
            return 1
        fi

        return 0
    }

    function ExecuteSetup
    {
        if ! "$_EXECUTE_MULTIBOOT_SETUP" \
            && ! "$_EXECUTE_STATIC_SETUP" \
            && ! "$_EXECUTE_UNINSTALL_SETUP"; then
            for _TRIES_COUNT in $( seq 0 2 ); do
                read -r -p "Execute VFIO setup? [(M)ultiboot/(S)tatic/(U)ninstall]: " _ANSWER

                case "$_ANSWER" in
                    [Mm]* )
                        _EXECUTE_MULTIBOOT_SETUP=true
                        break;;

                    [Ss]* )
                        _EXECUTE_STATIC_SETUP=true
                        break;;

                    [Uu]* )
                        _EXECUTE_UNINSTALL_SETUP=true
                        break;;

                    * )
                        echo "Please answer M, S, or U.";;
                esac
            done

            if [[ "$_ANSWER" != [MmSsUu]* ]]; then
                echo -e "$_PREFIX_ERROR Failed to answer."
                return 1
            fi
        fi

        case true in
            "$_EXECUTE_MULTIBOOT_SETUP" )
                ExecuteMultibootSetup || return 1
                ;;

            "$_EXECUTE_STATIC_SETUP" )
                ExecuteStaticSetup || return 1
                ;;

            "$_EXECUTE_UNINSTALL_SETUP" )
                ExecuteUninstallSetup || return 1
                ;;
        esac

        return 0
    }

    function SetParamsForGRUBStaticSetup
    {
        local -ar _STATIC_DRIVER_LIST=( "${_VFIOPCI_DRIVER_LIST[@]}" "${_VGA_VFIOPCI_DRIVER_LIST[@]}" )
        local -ar _STATIC_HWID_LIST=( "${_VFIOPCI_HWID_LIST[@]}" "${_VGA_VFIOPCI_HWID_LIST[@]}" )
        local -a _BLACKLISTS_LIST=()
        local -a _INITRAMFS_LIST=()
        local -a _MODULES_LIST=()
        local _DRIVER_DELIM=""
        local _HWID_DELIM=""
        local _STATIC_PCISTUB_HWID_DELIM=""

        for _DRIVER in ${_STATIC_DRIVER_LIST[@]}; do
            if [[ "$_DRIVER" != "" ]]; then
                _DRIVER_DELIM+="$_DRIVER,"

                _BLACKLISTS_LIST+=(
                    "blacklist $_DRIVER"
                )

                _INITRAMFS_LIST+=(
                    "softdep $_DRIVER pre: vfio-pci"
                    "$_DRIVER"
                )

                _MODULES_LIST+=(
                    "softdep $_DRIVER pre: vfio-pci"
                )
            fi
        done

        for _HWID in ${_STATIC_HWID_LIST[@]}; do
            if [[ "$_HWID" != "" ]]; then
                _HWID_DELIM+="$_HWID,"
            fi
        done

        if [[ "${#_PCISTUB_HWID_LIST[@]}" -gt 0 ]]; then
            for _HWID in ${_PCISTUB_HWID_LIST[@]}; do
                if [[ "$_HWID" != "" ]]; then
                    _STATIC_PCISTUB_HWID_DELIM+="$_HWID,"
                fi
            done
        fi

        _DRIVER_DELIM="${_DRIVER_DELIM::-1}"
        _HWID_DELIM="${_HWID_DELIM::-1}"

        if [[ "${#_STATIC_PCISTUB_HWID_DELIM}" -gt 0 ]]; then
            _STATIC_PCISTUB_HWID_DELIM="${_STATIC_PCISTUB_HWID_DELIM::-1}"
        fi

        return 0
    }

    function SetParamsForNoGRUBStaticSetup
    {
        GetParamsForVFIOSetup || return 1
        local -a _FILE_CONTENTS_LIST=()
        local -ar _STATIC_DRIVER_LIST=( "${_VFIOPCI_DRIVER_LIST[@]}" "${_VGA_VFIOPCI_DRIVER_LIST[@]}" )
        local -ar _STATIC_HWID_LIST=( "${_PCISTUB_HWID_LIST[@]}" "${_VFIOPCI_HWID_LIST[@]}" "${_VGA_VFIOPCI_HWID_LIST[@]}" )
        local -a _BLACKLISTS_LIST=()
        local -a _INITRAMFS_LIST=()
        local -a _MODULES_LIST=()
        local _DRIVER_DELIM=""
        local _HWID_DELIM=""

        for _DRIVER in ${_STATIC_DRIVER_LIST[@]}; do
            if [[ "$_DRIVER" != "" ]]; then
                _DRIVER_DELIM+="$_DRIVER,"

                _BLACKLISTS_LIST+=(
                    "blacklist $_DRIVER"
                )

                _INITRAMFS_LIST+=(
                    "softdep $_DRIVER pre: vfio-pci"
                    "$_DRIVER"
                )

                _MODULES_LIST+=(
                    "softdep $_DRIVER pre: vfio-pci"
                )
            fi
        done

        for _HWID in ${_STATIC_HWID_LIST[@]}; do
            if [[ "$_HWID" != "" ]]; then
                _HWID_DELIM+="$_HWID,"
            fi
        done

        _DRIVER_DELIM="${_DRIVER_DELIM::-1}"
        _HWID_DELIM="${_HWID_DELIM::-1}"
        return 0
    }

    function SetParamsForMultibootSetup
    {
        GetParamsForVFIOSetup || return 1

        # <remarks> System configuration </remarks>
        local -ir _MAX_NUM_PARSE_KERNELS=3
        declare -ar _KERNELS_LIST=( $( ls -1 /boot/vmli* | cut -d 'z' -f 2 | sort -r | head -n $_MAX_NUM_PARSE_KERNELS ) )
        local _SYSTEM_DISK=$( df / | grep -iv 'filesystem' | cut -d '/' -f3 | cut -d ' ' -f1 )
        local _SYSTEM_DISTRO=$( lsb_release -i -s )
        local _SYSTEM_FSTYPE=$( blkid -s TYPE | grep $_SYSTEM_DISK | cut -d '"' -f2 )
        local _SYSTEM_KERNEL=$( uname -o )
        local _SYSTEM_OS=$( uname )
        local _SYSTEM_UUID=$( blkid -s UUID | grep $_SYSTEM_DISK | cut -d '"' -f2 )

        local -ar _MULTIBOOT_DRIVER_LIST=( "${_VFIOPCI_DRIVER_LIST[@]}" )
        local -ar _MULTIBOOT_HWID_LIST=( "${_PCISTUB_HWID_LIST[@]}" "${_VFIOPCI_HWID_LIST[@]}" )
        local _NO_VGA_DRIVER_DELIM=""
        local _NO_VGA_HWID_DELIM=""

        for _DRIVER in ${_MULTIBOOT_DRIVER_LIST[@]}; do
            if [[ "$_DRIVER" != "" ]]; then
                _NO_VGA_DRIVER_DELIM+="$_DRIVER,"
            fi
        done

        for _HWID in ${_MULTIBOOT_HWID_LIST[@]}; do
            if [[ "$_HWID" != "" ]]; then
                _NO_VGA_HWID_DELIM+="$_HWID,"
            fi
        done

        _NO_VGA_DRIVER_DELIM="${_NO_VGA_DRIVER_DELIM::-1}"
        _NO_VGA_HWID_DELIM="${_NO_VGA_HWID_DELIM::-1}"
        local _LINE_GRUB_CMDLINE_PREFIX=""
        _LINE_GRUB_CMDLINE_PREFIX+="$_LINE_GRUB_CMDLINE "
        _LINE_GRUB_CMDLINE_PREFIX+="$_LINE_GRUB_CMDLINE_ISOLCPU "
        _LINE_GRUB_CMDLINE_PREFIX+="$_OUTPUT_GRUB_CMDLINE_HUGEPAGES "

        # <remarks> Parse VGA VFIO IOMMU Groups. </remarks>
        for _IOMMU in ${_VGA_VFIOPCI_IOMMU_LIST[@]}; do
            local _VGA_DRIVER_DELIM=""
            local _VGA_HWID_DELIM=""

            if ExcludeGivenVGAIOMMUGroup "$_IOMMU"; then
                for _KERNEL in ${_KERNELS_LIST[@]}; do
                    local _LINE_GRUB_CMDLINE_TEMP=""
                    local _LINE_VFIOPCI_DRIVER="$_NO_VGA_DRIVER_DELIM"
                    _LINE_VFIOPCI_DRIVER=",$_VGA_DRIVER_DELIM"
                    _LINE_GRUB_CMDLINE_TEMP+="modprobe.blacklist=\"$_LINE_VFIOPCI_DRIVER\" "
                    local _LINE_VFIOPCI_HWID="$_NO_VGA_HWID_DELIM"
                    _LINE_VFIOPCI_HWID=",$_VGA_HWID_DELIM"
                    _LINE_GRUB_CMDLINE_TEMP+="vfio_pci.ids=\"$_LINE_VFIOPCI_HWID\" "
                    _LINE_GRUB_CMDLINE_TEMP="$_LINE_GRUB_CMDLINE_PREFIX${_LINE_GRUB_CMDLINE_TEMP::-1}"

                    # <remarks> Organize menu entry for excluded VGA group and given system kernel. </remarks>
                    _FILE_CONTENTS_LIST+=(
                        "menuentry $_SYSTEM_DISTRO, with $_SYSTEM_KERNEL $_KERNEL (VFIO, w/o IOMMU $_IOMMU, w/ boot VGA \"$str_device_name\") {"
                        "\tinsmod $_SYSTEM_FSTYPE"
                        "\tset root='/dev/disk/by-uuid/$_SYSTEM_UUID'"
                        "\t"'if [ x$feature_platform_search_hint = xy ]; then'"\n\t\t"'search --no-floppy --fs-uuid --set=root '"$_SYSTEM_UUID\n\t"'fi'
                        "\techo    'Loading $_SYSTEM_OS $_KERNEL ...'"
                        "\tlinux   /boot/vmlinuz-$_KERNEL root=UUID=$_SYSTEM_UUID $_LINE_GRUB_CMDLINE_TEMP"
                        "\tinitrd  /boot/initrd.img-$_KERNEL"
                    )
                done
            fi
        done

        if ! [[ "${#_FILE_CONTENTS_LIST[@]}" -eq 0 ]]; then
            echo -e "$_PREFIX_ERROR Multiboot setup output is empty."
            return 1
        fi

        return 0
    }

    function WriteFilesForGRUBStaticSetup
    {
        "$_HAS_EXECUTED_BACKUPS" || return 1
        IFS=$'\n'
        local -r _LINE_TO_MATCH="GRUB_CMDLINE_LINUX_DEFAULT="
        local _LINE_GRUB_CMDLINE_TEMP=""
        _LINE_GRUB_CMDLINE_TEMP+="$_LINE_GRUB_CMDLINE "
        _LINE_GRUB_CMDLINE_TEMP+="$_LINE_GRUB_CMDLINE_ISOLCPU "
        _LINE_GRUB_CMDLINE_TEMP+="$_OUTPUT_GRUB_CMDLINE_HUGEPAGES "
        _LINE_GRUB_CMDLINE_TEMP+="modprobe.blacklist=\"$_DRIVER_DELIM\" "
        _LINE_GRUB_CMDLINE_TEMP+="pci-stub.ids=\"$_STATIC_PCISTUB_HWID_DELIM\" "
        _LINE_GRUB_CMDLINE_TEMP+="vfio_pci.ids=\"$_HWID_DELIM\" "
        _LINE_GRUB_CMDLINE_TEMP="${_LINE_GRUB_CMDLINE_TEMP::-1}"
        local -r _LINE_GRUB_CMDLINE_DEFAULT="GRUB_CMDLINE_LINUX_DEFAULT=\"$_LINE_GRUB_CMDLINE_TEMP\""

        if ! sed -i "/$_LINE_TO_MATCH\"*\"/c\$_LINE_GRUB_CMDLINE_DEFAULT\"" "$_GRUB_FILE_PATH" \
            || ! sed -i "/## REPLACE_THIS_LINE*/c\${_INITRAMFS_LIST[*]}" "$_INITRAMFS_MODULES_FILE_PATH" \
            || ! sed -i "/options vfio_pci ids=*/c\options vfio_pci_ids=\"$_HWID_DELIM\"" "$_INITRAMFS_MODULES_FILE_PATH" \
            || ! sed -i "/vfio_pci ids=*/c\vfio_pci_ids=\"$_HWID_DELIM\"" "$_INITRAMFS_MODULES_FILE_PATH" \
            || ! echo "${_BLACKLISTS_LIST[*]}" >> "$_MODPROBE_BLACKLISTS_FILE_PATH" \
            || ! sed -i "/## REPLACE_THIS_LINE*/c\${_MODULES_LIST[*]}" "$_MODPROBE_VFIO_FILE_PATH" \
            || ! sed -i "/options vfio_pci ids=*/c\vfio_pci_ids=$_HWID_DELIM" "$_MODPROBE_VFIO_FILE_PATH" \
            || ! sed -i "/vfio_pci ids=*/c\vfio_pci_ids=$_HWID_DELIM" "$_MODULES_FILE_PATH"; then
            echo -e "$_PREFIX_ERROR Failed to overwrite target lines of files."
            return 1
        fi

        return 0
    }

    function WriteFilesForNoGRUBStaticSetup
    {
        "$_HAS_EXECUTED_BACKUPS" || return 1
        IFS=$'\n'
        local -r _LINE_TO_MATCH="GRUB_CMDLINE_LINUX_DEFAULT="
        local _LINE_GRUB_CMDLINE_TEMP=""
        _LINE_GRUB_CMDLINE_TEMP+="$_LINE_GRUB_CMDLINE "
        _LINE_GRUB_CMDLINE_TEMP+="$_LINE_GRUB_CMDLINE_ISOLCPU "
        _LINE_GRUB_CMDLINE_TEMP+="$_OUTPUT_GRUB_CMDLINE_HUGEPAGES "
        _LINE_GRUB_CMDLINE_TEMP="${_LINE_GRUB_CMDLINE_TEMP::-1}"
        local -r _LINE_GRUB_CMDLINE_DEFAULT="$_LINE_TO_MATCH\"$_LINE_GRUB_CMDLINE_TEMP\""

        if ! sed -i "/$_LINE_TO_MATCH\"*\"/c\$_LINE_GRUB_CMDLINE_DEFAULT\"" "$_GRUB_FILE_PATH"; then
            echo -e "$_PREFIX_ERROR Failed to overwrite target lines of files."
            return 1
        fi

        return 0
    }

    function WriteFilesForMultibootSetup
    {
        "$_HAS_EXECUTED_BACKUPS" || return 1
        IFS=$'\n'

        if ! [ echo -e "${_FILE_CONTENTS_LIST[*]}" "$_CUSTOM_GRUB_FILE_PATH" ]; then
            echo -e "$_PREFIX_ERROR Failed to overwrite target lines of files."
            return 1
        fi

        return 0
    }
# </code>