#!/bin/bash sh

#
# Filename:         vfiolib-extras
# Description:      Recommended post-installation setups.
# Author(s):        Alex Portell <github.com/portellam>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

# <remarks> Using </remarks>
# <code>
    source vfiolib-calcs
    source vfiolib-iommu
# </code>

# <params>
    declare -g _GIT_PATH="$USER/source/"

    # <remarks> Flags </remarks>
    declare -g _IS_AUDIO_CAPTURE_SETUP=false
    declare -g _IS_SCREAM_SETUP=false
# </params>

# <code>
    # <summary>
    # zramswap: Setup a swap partition in host memory.
    # Reduce swapiness to existing host swap partition(s)/file(s), and reduce chances of memory exhaustion as host over-allocates memory.
    # </summary>
    function AllocateRAMToSwap
    {
        function Install
        {
            local -r _USER_NAME="foundObjects"
            local -r _REPO_NAME="zram-swap"
            local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
            local -r _SCRIPT_NAME="install.sh"

            echo
            UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" "$_EXECUTE_ZRAM_SWAP" || return 1
            cd "$_GIT_PATH$_FULL_REPO" || return 1

            if [[ -z "$_SCRIPT_NAME" ]]; then
                echo -e "$_PREFIX_ERROR Failed to find script '$_SCRIPT_NAME'."
                return 1
            fi

            if ! sudo bash "$_SCRIPT_NAME"; then
                echo -e "$_PREFIX_ERROR Failed to execute script '$_SCRIPT_NAME'."
                return 1
            fi

            return 0
        }

        function Modify
        {
            local -r _FILE="/etc/default/zram-swap"
            local -r _LINE_TO_MATCH="_zram_fraction="
            local -ir _ZRAM_SWAP_AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY / 2 ))
            local -ir _DENOMINATOR=$( printf "%.0f" $( echo "scale=2;$_INT_MAX_MEMORY/$_ZRAM_SWAP_AVAILABLE_MEMORY" | bc ) )

            # <remarks> Round down to nearest even number. </remarks>
            if [[ $( expr $_DENOMINATOR % 2 ) -eq 1 ]]; then
                (( _DENOMINATOR-- ))
            fi

            # <remarks> Is fraction positive non-zero and not equal to one. </remarks>
            if [[ "$_DENOMINATOR" -le 0 ]]; then
                echo -e "$_PREFIX_ERROR Denominator is negative or zero."
            fi

            local -r _FRACTION="1/$_DENOMINATOR"

            if ! sed -i "/$_LINE_TO_MATCH\"*\"/c\$_LINE_TO_MATCH\"$_FRACTION\"" "$_FILE"; then
                echo -e "$_PREFIX_ERROR Failed to write output to zram-swap file."
                return 1
            fi

            if sudo swapon -v | grep zram \
                && ! sudo swapon -v | grep zram | grep 0B; then
                echo -e "$_PREFIX_NOTE zram-swap device(s) already in use. Restart system to save changes."
                return 0
            fi

            if sudo swapon -v | grep zram \
                && ! sudo swapoff /dev/zram*; then
                echo -e "$_PREFIX_ERROR Failed to disable zram-swap device(s)."
                return 1
            fi

            if ! sudo systemctl daemon-reload &> /dev/null then
                echo -e "$_PREFIX_ERROR Failed to update systemd."
                return 1
            fi

            if ! sudo systemctl restart zram-swap; then
                echo -e "$_PREFIX_ERROR Failed to restart zram-swap service."
                return 1
            fi

            if ! sudo swapon -a; then
                echo -e "$_PREFIX_ERROR Failed to enable zram-swap device."
                return 1
            fi

            return 0
        }

        if ! IsHostMemorySufficientForZramSwap \
            || ! Install \
            || ! Modify &> /dev/null; then
            false
        fi

        PrintPassOrFail "Allocating RAM to swap..."
        return "$_LAST_EXIT_CODE"
    }

    function ExecuteExtras
    {
        GuestAudioCapture

        if "$_EXECUTE_ALL_EXTRAS_SETUPS"; then
            AllocateRAMToSwap
            SetVideoOutput
            LibvirtHooks
            GuestAudioLoopback
            GuestAudioStream
            GuestVideoCapture
            return 0
        fi

        if "$_EXECUTE_ZRAM_SWAP"; then
            AllocateRAMToSwap || return 1
        fi

        if "$_EXECUTE_AUTO_XORG_SETUP"; then
            SetVideoOutput || return 1
        fi

        if "$_EXECUTE_LIBVIRT_HOOKS"; then
            LibvirtHooks || return 1
        fi

        if "$_EXECUTE_AUDIO_LOOPBACK_SETUP"; then
            GuestAudioLoopback || return 1
        fi

        if "$_EXECUTE_SCREAM"; then
            GuestAudioStream || return 1
        fi

        if "$_EXECUTE_LOOKING_GLASS"; then
            GuestVideoCapture || return 1
        fi

        ModifyQEMU || return 1
        return 0
    }

    # <summary>
    # Install necessary depenencies to setup an audio capture from guest emulated audio device to host audio backend.
    # Installs PulseAudio or ALSA.
    # </summary>
    # <remarks>
    # References:
    #   https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Passing_through_other_devices
    # </remarks>
    function GuestAudioCapture
    {
        function Main
        {
            # <params>
            local str_dependencies=""
            # </params>

            # <remarks> Install JACK and PipeWire. </remarks>
            case "${_PACKAGE_MANAGER}" in
                "apt" )
                    str_dependencies+="pipewire pipewire-jack "
                    ;;

                "pacman" )
                    str_dependencies+="pipewire pipewire-jack "
                    ;;

                * )
                    return 1
            esac

            # <remarks> Include PulseAudio (and QEMU driver if available). </remarks>
            if IsInstalledCommand "pulseaudio" &> /dev/null; then
                case "${_PACKAGE_MANAGER}" in
                    "apt" )
                        str_dependencies+="pipewire-pulse "
                        ;;

                    "pacman" )
                        str_dependencies+="pipewire-pulse qemu-audio-pa "
                        ;;

                    * )
                        return 1
                esac

            # <remarks> Fallback to factory driver. </remarks>
            else
                case "${_PACKAGE_MANAGER}" in
                    "apt" )
                        str_dependencies+="pipewire-alsa "

                        ;;

                    "pacman" )
                        str_dependencies+="pipewire-alsa "
                        ;;

                    * )
                        return 1
                esac
            fi

            IsInstalledPackage "${str_dependencies}" || InstallPackage "${str_dependencies}"
            return "$?"
        }

        local _OUTPUT="Installing audio drivers..."
        Main &> /dev/null
        PrintPassOrFail "Installing audio drivers..." && _IS_AUDIO_CAPTURE_SETUP=true || _IS_AUDIO_CAPTURE_SETUP=false
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # Setup an audio loopback service from physical guest audio device (Line-Out) to physical host audio device (Line-In).
    # Requires physical connection between Line-Out and Line-In, and audio backend with JACK support (requires PulseAudio or ALSA).
    # </summary>
    function GuestAudioLoopback
    {
        function Main
        {
            # <remarks> Get audio backend. </remarks>
            if ! IsInstalledCommand "pulseaudio"; then
                return "$?"
            fi

            # <params>
            declare -a arr_file1_current _FILE_1_CONTENTS=(
                "[Unit]"
                "Description=Load audio loopback module"
                "After=pulseaudio.service"
                ""
                "[Service]"
                "Type=simple"
                "ExecStart=pactl load-module module-loopback"
                "ExecStop=pactl unload-module module-loopback"
                "RemainAfterExit=yes"
                ""
                "[Install]"
                "WantedBy=default.target"
            )

            local _PATH_1="/etc/systemd/system/"
            local _FILE_1="audio-loopback-user.service"
            # </params>

            if ! IsFile "${_FILE_1}" &> /dev/null || ( ReadFile "arr_file1_current" "${_FILE_1}" && IsArray "arr_file1_current" && ! AreEqualArrays "arr_file1_current" "_FILE_1_CONTENTS" ); then
                OverwriteFile "_FILE_1_CONTENTS" "${_PATH_1}${_FILE_1}" || return 1
            fi

            systemctl daemon-reload || return 1
            systemctl enable "${_FILE_1}" || return 1
            systemctl restart "${_FILE_1}" || return 1
            return 0
        }

        local _OUTPUT="Creating audio loopback..."
        Main &> /dev/null
        PrintPassOrFail "${_OUTPUT}"
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # Scream: Setup an audio stream from guest to host.
    # Requires virtual network bridge between guest and host, and operating systems Windows 7/8/10/11.
    # </summary>
    # <remarks>
    # References:
    #   https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Passing_audio_from_virtual_machine_to_host_via_Scream
    # </remarks>
    function GuestAudioStream
    {
        function Build
        {
            echo

            # <remarks> Build client </remarks>
            IsFile "build" || ( mkdir build || return 1 )
            cd build || return 1
            cmake .. || return 1
            make || return 1
            return 0
        }

        function Get
        {
            # <params>
            local _USER_NAME="duncanthrax"
            local _REPO_NAME="scream"
            local _FULL_REPO="${_USER_NAME}/${_REPO_NAME}"
            local str_dependencies=""
            # </params>

            # <remarks> Set dependencies for successful build. </remarks>
            case "${_PACKAGE_MANAGER}" in
                "apt" )
                    str_dependencies="cmake "
                    ;;

                "yum" )
                    str_dependencies="cmake "
                    ;;

                * )
                    return "$?"
                    ;;
            esac

            # <remarks> Set dependencies for available audio backend. </remarks>
            if IsInstalledCommand "pulseaudio"; then
                case "${_PACKAGE_MANAGER}" in
                    "apt" )
                        str_dependencies+="libpulse-dev "
                        ;;

                    "yum" )
                        str_dependencies+="pulseaudio-libs-devel "
                        ;;

                   * )
                        return "$?"
                        ;;
                esac
            elif IsInstalledCommand "pipewire-alsa"; then
                case "${_PACKAGE_MANAGER}" in
                    "apt" )
                        str_dependencies+="ibasound2-dev "
                        ;;

                    "yum" )
                        str_dependencies+="alsa-lib-devel "
                        ;;

                    * )
                        return "$?"
                        ;;
                esac
            else
                return 1
            fi

            # <remarks> Get dependencies. </remarks>
            if ! IsInstalledPackage "${str_dependencies}" &> /dev/null; then
                echo
                InstallPackage "${str_dependencies}" || return 1
                echo
            fi

            GetScriptDir
            echo
            UpdateOrCloneGitRepo "${_GIT_PATH}" "${_FULL_REPO}" "${_USER_NAME}" || return 1
            GetScriptDir
            cd "${_GIT_PATH}${_FULL_REPO}" || return 1
            return 0
        }

        function Install
        {
            # <params>
            declare -a arr_file1_current _FILE_1_CONTENTS arr_file2_contents
            local str_audio_backend_command str_audio_backend_name
            local _PATH_1="/etc/systemd/system/"
            local _FILE_1="audio-loopback-user.service"
            local str_dir2="${str_user_home_dir}/config/systemd/user/"
            local str_file2="scream-ivshmem-pulse.service"
            # </params>

            # <remarks> Get audio backend. </remarks>
            if ! IsInstalledCommand "pulseaudio" && ! IsInstalledCommand "pipewire"; then
                return "$?"
            elif IsInstalledCommand "pulseaudio" &> /dev/null; then
                str_audio_backend_name="PulseAudio"
            else
                str_audio_backend_name="PipeWire"
            fi

            str_audio_backend_command=$( echo $str_audio_backend_name | tr '[:upper:]' '[:lower:]' )

            arr_file_contents=(
                "[Unit]"
                "Description=${str_audio_backend_name} - QEMU"
                "ConditionUser=!root"
                ""
                "[Socket]"
                "Service=${str_audio_backend_command}-pulse.service"
                "Priority=6"
                "ListenStream=%T/${str_audio_backend_command}-qemu"
                "SocketGroup=libvirt-qemu"
                "SocketMode=0660"
                ""
                "[Install]"
                "RequiredBy=${str_audio_backend_command}-pulse.service"
                "WantedBy=sockets.target"
            )

            declare -a arr_file2_contents=(
                "[Unit]"
                "Description=Scream IVSHMEM pulse receiver"
                "After=${str_audio_backend_command}.service"
                "Wants=${str_audio_backend_command}.service"
                ""
                "[Service]"
                "Type=simple"
                "ExecStartPre=/usr/bin/truncate -s 0 /dev/shm/scream-ivshmem"
                "ExecStartPre=/usr/bin/dd if=/dev/zero of=/dev/shm/scream-ivshmem bs=1M count=2"
                "ExecStart=/usr/bin/scream -m /dev/shm/scream-ivshmem"
                ""
                "[Install]"
                "WantedBy=default.target"
            )

            if ! IsFile "${_FILE_1}" &> /dev/null || ( ReadFile "arr_file1_current" "${_FILE_1}" && IsArray "arr_file1_current" && ! AreEqualArrays "arr_file1_current" "_FILE_1_CONTENTS" ); then
                OverwriteFile "_FILE_1_CONTENTS" "${_PATH_1}${_FILE_1}" || return 1
            fi

            if ! IsFile "${str_file2}" &> /dev/null || ( ReadFile "arr_file2_current" "${str_file2}" && IsArray "arr_file2_current" && ! AreEqualArrays "arr_file2_current" "arr_file2_contents" ); then
                OverwriteFile "arr_file2_contents" "${str_dir2}${str_file2}" || return 1
            fi

            systemctl daemon-reload || return 1
            systemctl enable "${_FILE_1}" || return 1
            systemctl restart "${_FILE_1}" || return 1
            return 0
        }

        if ! GuestAudioCapture; then
            local _OUTPUT="Installing Scream...\t"
            (return "${int_code_skipped_operation}")
        else
            local _OUTPUT="Updating Scream..."
            # PrintWait "${_OUTPUT}"
            Get &> /dev/null
            PrintPassOrFail "${_OUTPUT}"

            local _OUTPUT="Building Scream..."
            # PrintWait "${_OUTPUT}"

            if Build; then
                PrintPassOrFail "${_OUTPUT}"

                local _OUTPUT="Installing Scream...\t"
                # PrintWait "${_OUTPUT}"
                Install
            fi
        fi

        PrintPassOrFail "${_OUTPUT}" && _IS_SCREAM_SETUP=true
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # LookingGlass: Setup direct-memory-access of video framebuffer (and audio?) from guest to host.
    # Requires operating systems Windows 7/8/10/11.
    # </summary>
    # <remarks>
    # References:
    #   https://looking-glass.io/docs/B6/install/#client-install
    # </remarks>
    function GuestVideoCapture
    {
        function Get
        {
            # <params>
            local _USER_NAME="gnif"
            local _REPO_NAME="LookingGlass"
            local _FULL_REPO="${_USER_NAME}/${_REPO_NAME}"
            local str_dependencies=""
            # </params>

            case "${_PACKAGE_MANAGER}" in
                "apt" )
                    str_dependencies="cmake gcc g++ clang libegl-dev libgl-dev libgles-dev libfontconfig-dev libgmp-dev libspice-protocol-dev make nettle-dev pkg-config"
                    ;;

                # "yum" )
                #     local str_package=""
                #     ;;
            esac

            if ! IsInstalledPackage "${str_dependencies}" &> /dev/null; then
                echo
                InstallPackage "${str_dependencies}" || return 1
                echo
            fi

            GetScriptDir
            echo
            UpdateOrCloneGitRepo "${_GIT_PATH}" "${_FULL_REPO}" "${_USER_NAME}" || return 1
            GetScriptDir
            cd "${_GIT_PATH}${_FULL_REPO}" || return 1
            return 0
        }

        function Install
        {
            echo

            # <remarks> Build client </remarks>
            if [[ -z "client/build" ]]; then
                mkdir client/build || return 1
            fi

            cd client/build || return 1
            cmake ../ || ( git submodule update --init --recursive && cmake ../ ) || return 1
            make || return 1                                                            # TODO: fix here!

            # <remarks> Conclude build as root or user. </remarks>
            if [[ $( whoami ) != "root" ]]; then
                make install || return 1
            else
                cmake -DCMAKE_INSTALL_PREFIX=~/.local .. && make install
            fi

            return 0
        }

        Get
        PrintPassOrFail "Updating LookingGlass..."
        Install
        PrintPassOrFail "Installing LookingGlass..."
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # libvirt-hooks: Setup useful Quality-of-life improvements in the form of services and scripts (hooks) for QEMU guest(s).
    # </summary>
    function LibvirtHooks
    {
        function Main
        {
            if ! sudo cp "$_LIBVIRT_HOOK_NOSLEEP_FILE_BACKUP" "$_LIBVIRT_HOOK_NOSLEEP_FILE_PATH"; then
                echo -e "$_PREFIX_ERROR Failed to copy file."
                return 1
            fi

            if ! sudo systemctl daemon-reload &> /dev/null then
                echo -e "$_PREFIX_ERROR Failed to update systemd with new daemon/service."
                return 1
            fi

            return 0
        }

        Main
        PrintPassOrFail "Installing libvirt-hooks..."
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # auto-Xorg: System service to find and set a valid Host boot VGA device for Xorg.
    # </summary>
    # <remarks>
    # References:
    #   https://github.com/portellam/auto-Xorg
    # </remarks>
    function SetVideoOutput
    {
        # TODO
        return 1
    }

    function UpdateOrCloneGitRepo
    {
        local _AUTO_ANSWER_YES=false

        if [[ "$4" == true ]]; then
            _AUTO_ANSWER_YES=true
        fi

        if [[ "$3" == "" ]] \
            || [[ "$2" == "" ]] \
            || [[ "$1" == "" ]]; then
            echo -e "$_PREFIX_ERROR Input values are empty."
            return 1
        fi

        if [[ ! -d "$1$2" ]] \
            && sudo mkdir -p "$1$3"; then
            echo -e "$_PREFIX_ERROR Failed to create directory '$1$3'."
            return 1
        fi

        # <remarks> Update existing GitHub repository. </remarks>
        if [[ -d "$1$2" ]]; then
            cd "$1$2"

            if ! git pull &> /dev/null; then
                echo -e "$_PREFIX_ERROR Failed to update repository."
                return 1
            fi

            return 0

        # <remarks> Clone new GitHub repository. </remarks>
        elif [[ -d "$1$3" ]]; then
            for _TRIES_COUNT in $( seq 0 2 ); do
                if ! "$_AUTO_ANSWER_YES"; then
                    read -r -p "Clone repo '$2'? [Y/n]: " _ANSWER
                else
                    _ANSWER="Y"
                fi

                case "$_ANSWER" in
                    [Yy]* )
                        cd "$1$3"

                        if ! git clone "https://github.com/$2" &> /dev/null; then
                            echo -e "$_PREFIX_ERROR Failed to download repository."
                            return 1
                        fi

                        return 0 ;;

                    [Nn]* )
                        break ;;

                    * )
                        echo "Please answer Y/n." ;;
                esac
            done

            return 1

        else
            return 1
        fi
    }
# </code>