#!/bin/bash sh

#
# Filename:         vfiolib-extras
# Description:      Recommended post-installation setups.
# Author(s):        Alex Portell <github.com/portellam>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

# <remarks> Using </remarks>
# <code>
    source vfiolib-calcs
    source vfiolib-common
    source vfiolib-iommu
# </code>

# <params>
    declare -g _GIT_PATH="$USER/source/"

    # <remarks> Flags </remarks>
    declare -g _IS_AUDIO_CAPTURE_SETUP=false
    declare -g _IS_SCREAM_SETUP=false
# </params>

# <code>
    # <summary>
    # zramswap: Setup a swap partition in host memory.
    # Reduce swapiness to existing host swap partition(s)/file(s), and reduce chances of memory exhaustion as host over-allocates memory.
    # </summary>
    function AllocateRAMToSwap
    {
        function Get
        {
            echo
            UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" "$_EXECUTE_ZRAM_SWAP" || return 1
            return 0
        }

        function Install
        {
            local -r _SCRIPT_NAME="install.sh"

            if ! cd "$_GIT_PATH$_FULL_REPO"; then
                echo -e "$_PREFIX_ERROR Failed to find build directory."
                return 1
            fi

            if [[ -z "$_SCRIPT_NAME" ]]; then
                echo -e "$_PREFIX_ERROR Failed to find script '$_SCRIPT_NAME'."
                return 1
            fi

            if ! sudo bash "$_SCRIPT_NAME"; then
                echo -e "$_PREFIX_ERROR Failed to execute script '$_SCRIPT_NAME'."
                return 1
            fi

            return 0
        }

        function Modify
        {
            local -r _FILE="/etc/default/zram-swap"
            local -r _LINE_TO_MATCH="_zram_fraction="
            local -ir _ZRAM_SWAP_AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY / 2 ))
            local -ir _DENOMINATOR=$( printf "%.0f" $( echo "scale=2;$_INT_MAX_MEMORY/$_ZRAM_SWAP_AVAILABLE_MEMORY" | bc ) )

            # <remarks> Round down to nearest even number. </remarks>
            if [[ $( expr $_DENOMINATOR % 2 ) -eq 1 ]]; then
                (( _DENOMINATOR-- ))
            fi

            # <remarks> Is fraction positive non-zero and not equal to one. </remarks>
            if [[ "$_DENOMINATOR" -le 0 ]]; then
                echo -e "$_PREFIX_ERROR Denominator is negative or zero."
            fi

            local -r _FRACTION="1/$_DENOMINATOR"

            if ! sed -i "/$_LINE_TO_MATCH\"*\"/c\$_LINE_TO_MATCH\"$_FRACTION\"" "$_FILE"; then
                echo -e "$_PREFIX_ERROR Failed to write output to zram-swap file."
                return 1
            fi

            if sudo swapon -v | grep zram \
                && ! sudo swapon -v | grep zram | grep 0B; then
                echo -e "$_PREFIX_NOTE zram-swap device(s) already in use. Restart system to save changes."
                return 0
            fi

            if sudo swapon -v | grep zram \
                && ! sudo swapoff /dev/zram*; then
                echo -e "$_PREFIX_ERROR Failed to disable zram-swap device(s)."
                return 1
            fi

            if ! sudo systemctl daemon-reload &> /dev/null then
                echo -e "$_PREFIX_ERROR Failed to update systemd."
                return 1
            fi

            if ! sudo systemctl restart zram-swap; then
                echo -e "$_PREFIX_ERROR Failed to restart zram-swap service."
                return 1
            fi

            if ! sudo swapon -a; then
                echo -e "$_PREFIX_ERROR Failed to enable zram-swap device."
                return 1
            fi

            return 0
        }

        if ! IsHostMemorySufficientForZramSwap \
            || ! Install \
            || ! Modify &> /dev/null; then
            false
        fi

        local -r _USER_NAME="foundObjects"
        local -r _REPO_NAME="zram-swap"
        local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
        PrintPassOrFail "Allocating RAM to swap..."
        return "$_LAST_EXIT_CODE"
    }

    function ExecuteExtras
    {
        if "$_EXECUTE_ALL_EXTRAS_SETUPS"; then
            AllocateRAMToSwap
            SetVideoOutput
            LibvirtHooks
            GuestAudioLoopback
            GuestAudioStream
            GuestVideoCapture
            return 0
        fi

        if "$_EXECUTE_ZRAM_SWAP"; then
            AllocateRAMToSwap || return 1
        fi

        if "$_EXECUTE_AUTO_XORG_SETUP"; then
            SetVideoOutput || return 1
        fi

        if "$_EXECUTE_LIBVIRT_HOOKS"; then
            LibvirtHooks || return 1
        fi

        if "$_EXECUTE_AUDIO_LOOPBACK_SETUP"; then
            GuestAudioLoopback || return 1
        fi

        if "$_EXECUTE_SCREAM"; then
            GuestAudioStream || return 1
        fi

        if "$_EXECUTE_LOOKING_GLASS"; then
            GuestVideoCapture || return 1
        fi

        ModifyQEMU || return 1
        return 0
    }

    # <summary>
    # Install necessary depenencies to setup an audio capture from guest emulated audio device to host audio backend.
    # Installs PulseAudio or ALSA.
    # </summary>
    # <remarks>
    # References:
    #   https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Passing_through_other_devices
    # </remarks>
    function GuestAudioCapture
    {
        function Main
        {
            local _DEPENDENCIES=""

            # <remarks> Install JACK and PipeWire. </remarks>
            case "$_PACKAGE_MANAGER" in
                "apt" )
                    _DEPENDENCIES+="pipewire pipewire-jack " ;;

                "pacman" )
                    _DEPENDENCIES+="pipewire pipewire-jack " ;;

                * )
                    echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
                    return 1 ;;
            esac

            # <remarks> Include PulseAudio (and QEMU driver if available). </remarks>
            if IsInstalledCommand "pulseaudio" &> /dev/null; then
                case "$_PACKAGE_MANAGER" in
                    "apt" )
                        _DEPENDENCIES+="pipewire-pulse " ;;

                    "pacman" )
                        _DEPENDENCIES+="pipewire-pulse qemu-audio-pa " ;;

                    * )
                        echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
                        return 1 ;;
                esac

            # <remarks> Fallback to factory driver. </remarks>
            else
                case "$_PACKAGE_MANAGER" in
                    "apt" )
                        _DEPENDENCIES+="pipewire-alsa " ;;

                    "pacman" )
                        _DEPENDENCIES+="pipewire-alsa " ;;

                    * )
                        echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
                        return 1 ;;
                esac
            fi

            IsInstalledPackage "$_DEPENDENCIES" || InstallPackage "$_DEPENDENCIES"
            return "$?"
        }

        local _OUTPUT="Installing audio drivers..."
        Main
        PrintPassOrFail "Installing audio drivers..." && _IS_AUDIO_CAPTURE_SETUP=true || _IS_AUDIO_CAPTURE_SETUP=false
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # Setup an audio loopback service from physical guest audio device (Line-Out) to physical host audio device (Line-In).
    # Requires physical connection between Line-Out and Line-In, and audio backend with JACK support (requires PulseAudio or ALSA).
    # </summary>
    function GuestAudioLoopback
    {
        function Main
        {
            if ! command -v "pulseaudio"; then
                echo -e "$_PREFIX_ERROR Required audio backend 'PulseAudio' is missing."
                return 1
            fi

            if ! sudo cp "$_AUDIO_LOOPBACK_FILE_BACKUP" "$_AUDIO_LOOPBACK_FILE_PATH"; then
                echo -e "$_PREFIX_ERROR Failed to copy file."
                return 1
            fi

            if ! sudo systemctl daemon-reload &> /dev/null then
                echo -e "$_PREFIX_ERROR Failed to update systemd with new daemon/service."
                return 1
            fi

            if ! sudo systemctl start "$_AUDIO_LOOPBACK_FILE_BACKUP"; then
                echo -e "$_PREFIX_ERROR Failed to start audio loopback service."
                return 1
            fi

            if ! sudo systemctl enable "$_AUDIO_LOOPBACK_FILE_BACKUP"; then
                echo -e "$_PREFIX_ERROR Failed to enable audio loopback service."
                return 1
            fi

            return 0
        }

        Main
        PrintPassOrFail "Creating audio loopback..."
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # Scream: Setup an audio stream from guest to host.
    # Requires virtual network bridge between guest and host, and operating systems Windows 7/8/10/11.
    # </summary>
    # <remarks>
    # References:
    #   https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Passing_audio_from_virtual_machine_to_host_via_Scream
    # </remarks>
    function GuestAudioStream
    {
        function Build
        {
            echo

            if [[ -z "build" ]] \
                && ! mkdir build; then
                echo -e "$_PREFIX_ERROR Failed to create build directory."
                return 1
            fi

            if ! cd build; then
                echo -e "$_PREFIX_ERROR Failed to find build directory."
                return 1
            fi

            if ! cmake .. \
                && ! make; then
                echo -e "$_PREFIX_ERROR Failed to build client."
                return 1
            fi

            return 0
        }

        function Get
        {
            local _USER_NAME="duncanthrax"
            local _REPO_NAME="scream"
            local _FULL_REPO="$_USER_NAME/$_REPO_NAME"
            local _DEPENDENCIES=""

            # <remarks> Set dependencies for successful build. </remarks>
            case "$_PACKAGE_MANAGER" in
                "apt" | "yum" )
                    _DEPENDENCIES="cmake " ;;

                * )
                    return 1
                    ;;
            esac

            # <remarks> Set dependencies for available audio backend. </remarks>
            if command -v "pulseaudio"; then
                case "$_PACKAGE_MANAGER" in
                    "apt" )
                        _DEPENDENCIES+="libpulse-dev " ;;

                    "yum" )
                        _DEPENDENCIES+="pulseaudio-libs-devel " ;;

                   * )
                        return 1 ;;
                esac

            elif command -v "pipewire-alsa"; then
                case "$_PACKAGE_MANAGER" in
                    "apt" )
                        _DEPENDENCIES+="ibasound2-dev " ;;

                    "yum" )
                        _DEPENDENCIES+="alsa-lib-devel " ;;

                    * )
                        return 1 ;;
                esac

            else
                return 1
            fi

            # <remarks> Get dependencies. </remarks>
            if ! IsInstalledPackage "$_DEPENDENCIES" &> /dev/null; then
                echo
                InstallPackage "$_DEPENDENCIES" || return 1
                echo
            fi

            echo
            UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" "$_EXECUTE_SCREAM" || return 1
            cd "$_GIT_PATH$_FULL_REPO" || return 1
            return 0
        }

        function Install
        {
            if command -v "pulseaudio"; then
                if ! sudo cp "$_SCREAM_PULSEAUDIO_FILE_BACKUP" "$_SCREAM_PULSEAUDIO_FILE_PATH"; then
                    echo -e "$_PREFIX_ERROR Failed to copy file."
                    return 1
                fi

                if ! sudo systemctl daemon-reload &> /dev/null then
                    echo -e "$_PREFIX_ERROR Failed to update systemd with new daemon/service."
                    return 1
                fi

                if ! sudo systemctl start $_SCREAM_PULSEAUDIO_FILE_BACKUP; then
                    echo -e "$_PREFIX_ERROR Failed to start Scream shared memory service."
                    return 1
                fi

                if ! sudo systemctl enable $_SCREAM_PULSEAUDIO_FILE_BACKUP; then
                    echo -e "$_PREFIX_ERROR Failed to enable Scream shared memory service."
                    return 1
                fi

                return 0
            fi

            if command -v "pipewire"; then
                if ! sudo cp "$_SCREAM_PIPEWIRE_FILE_BACKUP" "$_SCREAM_PIPEWIRE_FILE_PATH"; then
                    echo -e "$_PREFIX_ERROR Failed to copy file."
                    return 1
                fi

                if ! sudo systemctl daemon-reload &> /dev/null then
                    echo -e "$_PREFIX_ERROR Failed to update systemd with new daemon/service."
                    return 1
                fi

                if ! sudo systemctl start $_SCREAM_PIPEWIRE_FILE_BACKUP; then
                    echo -e "$_PREFIX_ERROR Failed to start Scream shared memory service."
                    return 1
                fi

                if ! sudo systemctl enable $_SCREAM_PIPEWIRE_FILE_BACKUP; then
                    echo -e "$_PREFIX_ERROR Failed to enable Scream shared memory service."
                    return 1
                fi

                return 0
            fi

            echo -e "$_PREFIX_ERROR Missing required audio backends (Pipewire, PulseAudio)."
            return 1
        }

        if ! GuestAudioCapture; then
            local _OUTPUT="Installing Scream...\t"
            false
        else
            local _OUTPUT="Updating Scream..."
            Get
            PrintPassOrFail "$_OUTPUT"

            local _OUTPUT="Building Scream..."

            if Build; then
                PrintPassOrFail "$_OUTPUT"
                local _OUTPUT="Installing Scream...\t"
                Install
            fi
        fi

        PrintPassOrFail "$_OUTPUT" && _IS_SCREAM_SETUP=true
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # LookingGlass: Setup direct-memory-access of video framebuffer (and audio?) from guest to host.
    # Requires operating systems Windows 7/8/10/11.
    # </summary>
    # <remarks>
    # References:
    #   https://looking-glass.io/docs/B6/install/#client-install
    # </remarks>
    function GuestVideoCapture
    {
        function Get
        {
            local _USER_NAME="gnif"
            local _REPO_NAME="LookingGlass"
            local _FULL_REPO="$_USER_NAME/$_REPO_NAME"
            local _DEPENDENCIES=""

            case "$_PACKAGE_MANAGER" in
                "apt" )
                    _DEPENDENCIES="cmake gcc g++ clang libegl-dev libgl-dev libgles-dev libfontconfig-dev libgmp-dev libspice-protocol-dev make nettle-dev pkg-config"
                    ;;

                * )
                    echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
                    return 1 ;;
            esac

            if ! IsInstalledPackage "$_DEPENDENCIES" &> /dev/null; then
                echo
                InstallPackage "$_DEPENDENCIES" || return 1
                echo
            fi

            echo
            UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" || return 1
            cd "$_GIT_PATH$_FULL_REPO" || return 1
            return 0
        }

        function Install
        {
            echo

            # <remarks> Build client </remarks>
            if [[ -z "client/build" ]] \
                && ! mkdir client/build; then
                echo -e "$_PREFIX_ERROR Failed to create build directory."
                return 1
            fi

            if ! cd client/build; then
                echo -e "$_PREFIX_ERROR Failed to find build directory."
                return 1
            fi

            if ! cmake ../ \
                && ! git submodule update --init --recursive \
                && ! cmake ../; then
                echo -e "$_PREFIX_ERROR Failed cmake"
                return 1
            fi

            if ! make; then
                echo -e "$_PREFIX_ERROR Failed make."
                return 1
            fi

            # <remarks> Conclude build as root or user. </remarks>
            if [[ $( whoami ) != "root" ]]; then
                if ! make install; then
                    echo -e "$_PREFIX_ERROR Failed to build."
                    return 1
                fi
            else
                if ! cmake -DCMAKE_INSTALL_PREFIX=~/.local .. \
                    && make install; then
                    echo -e "$_PREFIX_ERROR Failed to build."
                    return 1
                fi
            fi

            return 0
        }

        Get
        PrintPassOrFail "Updating LookingGlass..."
        Install
        PrintPassOrFail "Installing LookingGlass..."
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # libvirt-hooks: Setup useful Quality-of-life improvements in the form of services and scripts (hooks) for QEMU guest(s).
    # </summary>
    function LibvirtHooks
    {
        function Main
        {
            if ! sudo cp "$_LIBVIRT_HOOK_NOSLEEP_FILE_BACKUP" "$_LIBVIRT_HOOK_NOSLEEP_FILE_PATH"; then
                echo -e "$_PREFIX_ERROR Failed to copy file."
                return 1
            fi

            if ! sudo systemctl daemon-reload &> /dev/null then
                echo -e "$_PREFIX_ERROR Failed to update systemd with new daemon/service."
                return 1
            fi

            return 0
        }

        Main
        PrintPassOrFail "Installing libvirt-hooks..."
        return "$_LAST_EXIT_CODE"
    }

    # <summary>
    # auto-Xorg: System service to find and set a valid Host boot VGA device for Xorg.
    # </summary>
    # <remarks>
    # References:
    #   https://github.com/portellam/auto-Xorg
    # </remarks>
    function SetVideoOutput
    {
        function Get
        {
            echo
            UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" "$_EXECUTE_AUTO_XORG_SETUP" || return 1
            return 0
        }

        function Install
        {
            local -r _SCRIPT_NAME="installer.bash"

            if ! cd "$_GIT_PATH$_FULL_REPO"; then
                echo -e "$_PREFIX_ERROR Failed to find build directory."
                return 1
            fi

            if [[ -z "$_SCRIPT_NAME" ]]; then
                echo -e "$_PREFIX_ERROR Failed to find script '$_SCRIPT_NAME'."
                return 1
            fi

            if ! sudo bash "$_SCRIPT_NAME"; then                                    # TODO: add input vars here!
                echo -e "$_PREFIX_ERROR Failed to execute script '$_SCRIPT_NAME'."
                return 1
            fi

            return 0
        }

        local -r _USER_NAME="portellam"
        local -r _REPO_NAME="auto-Xorg"
        local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
        Get
        Install
        PrintPassOrFail "Allocating RAM to swap..."
        return "$_LAST_EXIT_CODE"
    }
# </code>