#!/bin/bash sh

#
# Filename:         vfiolib-usage
# Description:      Usage
# Author(s):        Alex Portell <github.com/portellam>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

# <remarks> Using </remarks>
# <code>
    source vfiolib-calc
# </code>

# <params>
    declare -gr _OUTPUT_INVALID_ANSWER="$_PREFIX_ERROR Failed to answer."
    declare -gr _OUTPUT_INVALID_OPTION="$_PREFIX_ERROR Invalid option."

    # <remarks> Get script directories </remarks
    GetScriptDir
    declare -g _FILES_PATH="$( find . -name files | uniq | head -n1 | cut -c2- )/"
    declare -g _FILENAME_PARSE_IOMMU=""

    # <remarks> Toggles </remarks
    declare -g _IS_CONNECTED_TO_INTERNET=false

    # <remarks> Usage toggles </remarks
    declare -g _EXECUTE_ALL_EXTRAS_SETUPS=true
    declare -g _EXECUTE_ALL_UTILS_SETUPS=true
    declare -g _EXECUTE_ISOLCPU_SETUP=false
    declare -g _EXECUTE_AUDIO_LOOPBACK_SETUP=false
    declare -g _EXECUTE_AUTO_XORG_SETUP=false
    declare -g _EXECUTE_EVDEV_SETUP=false
    declare -g _IS_HUGEPAGES_COUNT_SET=false
    declare -g _IS_HUGEPAGES_SIZE_SET=false
    declare -g _EXECUTE_LIBVIRT_HOOKS=false
    declare -g _EXECUTE_LOOKING_GLASS=false
    declare -g _EXECUTE_MULTIBOOT_SETUP=false
    declare -g _PARSE_IOMMU_FROM_FILE=false
    declare -g _PARSE_IOMMU_FROM_CACHE=false
    declare -g _PARSE_IOMMU_FROM_INTERNET=false
    declare -g _EXECUTE_SCREAM=false
    declare -g _SELECT_ALL_IOMMU=false
    declare -g _EXECUTE_STATIC_SETUP=false
    declare -g _UNINSTALL_EXTRAS=false
    declare -g _UNINSTALL_UTILS=false
    declare -g _EXECUTE_UNINSTALL_SETUP=false
    declare -g _EXECUTE_ZRAM_SWAP=false
    declare -g _ZRAM_SWAP_OVERRIDE=false
    declare -g _ZRAM_SWAP_SET_FRACTION=false
# </params>

# <code>
    # <summary> Set arguments and options. </summary>
    # <param name="@"> array: the input parameters </param>
    function GetOption
    {
        while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
            "--help" )
                return 1
                ;;

            # <remarks> Pre-setup: Parse IOMMU </remarks>
            "-f" | "--file" )
                GetSelect_IOMMU_Args $2 || return "$?"
                IsFile $3 || return "$?"
                _FILENAME_PARSE_IOMMU=$3
                _PARSE_IOMMU_FROM_FILE=true
                ;;

            "-i" | "--internal" )
                GetSelect_IOMMU_Args $2 || return "$?"
                _PARSE_IOMMU_FROM_CACHE=true
                ;;

            "-o" | "--online" )
                GetSelect_IOMMU_Args $2 || return "$?"
                _PARSE_IOMMU_FROM_INTERNET=true
                ;;

            # <remarks> Pre-setup: Utilities </remarks>
            "-c" | "--cpu" )
                _EXECUTE_ALL_UTILS_SETUPS=false
                _EXECUTE_ISOLCPU_SETUP=true
                ;;

            "-e" | "--evdev" )
                _EXECUTE_ALL_UTILS_SETUPS=false
                _EXECUTE_EVDEV_SETUP=true
                ;;

            "-h" | "--hugepages" )
                _EXECUTE_ALL_UTILS_SETUPS=false

                if [[ "$2" != "" ]]; then
                    GetHugepageByteSize "$2" || return "$?"
                fi

                if [[ "$3" != "" ]]; then
                    GetHugepageCount "$3" || return "$?"
                fi
                ;;

            "--uninstall-utils" )
                _UNINSTALL_UTILS=true
                ;;

            # <remarks> Main setup </remarks>
            "-m" | "--multiboot" )
                GetArgsForStatic_VFIO $1 || return "$?"
                GetArgsForStatic_VFIO $2 || return "$?"
                _EXECUTE_MULTIBOOT_SETUP=true
                ;;

            "-s" | "--static" )
                _EXECUTE_STATIC_SETUP=true
                ;;

            "-u" | "--uninstall" )
                _EXECUTE_UNINSTALL_SETUP=true
                ;;

            # <remarks> Post-setup: Extras </remarks>
            "-H" | "--hooks" )
                _EXECUTE_ALL_EXTRAS_SETUPS=false
                _EXECUTE_LIBVIRT_HOOKS=true
                ;;

            "-l" | "--looking-glass" )
                _EXECUTE_ALL_EXTRAS_SETUPS=false
                _EXECUTE_LOOKING_GLASS=true
                ;;

            "-L" | "--audio-loopback" )
                _EXECUTE_ALL_EXTRAS_SETUPS=false
                _EXECUTE_AUDIO_LOOPBACK_SETUP=true
                ;;

            "-S" | "--scream" )
                _EXECUTE_ALL_EXTRAS_SETUPS=false
                _EXECUTE_SCREAM=true
                ;;

            "-x" | "--auto-xorg" )
                _EXECUTE_ALL_EXTRAS_SETUPS=false
                _EXECUTE_AUTO_XORG_SETUP=true
                ;;

            "-z" | "--zram-swap" )
                _EXECUTE_ALL_EXTRAS_SETUPS=false
                GetZramSwapSize $1 || return "$?"
                GetZramSwapOverride $2
                _EXECUTE_ZRAM_SWAP=true
                ;;

            "--uninstall-extras" )
                _UNINSTALL_EXTRAS=true
                ;;

            # <remarks> Else </remarks>
            "" )
                ;;

            * )
                echo -e "$_PREFIX_FAIL Invalid input."
                return 1
                ;;
        esac; shift; done

        if [[ "$1" == '--' ]]; then
            shift
        fi

        return 0
    }

    # <summary> Set option for given argument. </summary>
    # <param name="1"> string: the option </param>
    function GetArgsForStatic_VFIO
    {
        IsString $1 &> /dev/null || return 0

        case $1 in
            "grub" )
                _EXECUTE_STATIC_SETUP_grub=true
                return 0
                ;;

            "file" )
                _EXECUTE_STATIC_SETUP_file=true
                return 0
                ;;
        esac

        return 1
    }

    # <summary> Set option for given argument. </summary>
    # <param name="1"> string: the option </param>
    function GetSelect_IOMMU_Args
    {
        case "$1" in
            "all" )
                _SELECT_ALL_IOMMU=true
                ;;

            * )
                return 1
                ;;
        esac

        return 0
    }

    # <summary> Prints the usage. </summary>
    function GetUsage
    {
        IFS=$'\n'

        declare -a _OUTPUT=(
            "Usage:\t\tbash deploy-vfio [OPTION]... [ARGUMENTS]..."
            "Deploy a VFIO setup to a Linux Host that supports Para-virtualization or PCI Passthrough.\n"
            "  --help\tprint this help and exit"

            "\nParse IOMMU groups and reference chosen database for the system's PCI devices.\nOPTIONS: *"
            "  -f, --file [filename]\tReference file database."
            "  -i, --internal\tReference local database."
            "  -o, --online\t\tReference online database."

            "\nARGUMENTS: *"
            "  [filename]            Reference specific file."
            "  all\t\t\tSelect all IOMMU groups."
            "  no-vga\t\tSelect all IOMMU groups without VGA devices."
            "  [x-y,z]\t\tSelect specific IOMMU groups (comma separated, or ranges)."

            "\n  Example:"
            "    -f somefile.txt     Reference file 'somefile.txt' and begin parse."
            "    no-vga 14\t\tSelect group 14 and all non-VGA groups."
            "    1,14-16\t\tSelect groups 1, 14, 15, and 16."

            "\nPre-setup OPTIONS: *"
            "  -c, --cpu\t\t\tAllocate CPU."
            "  -e, --evdev\t\t\tSetup a virtual KVM switch."
            "  -h, --hugepages\t\tCreate static hugepages (pages greater than 4 KiB) to allocate RAM for Guest(s)."
            "  --uninstall-utils\t\tUndo changes made by preliminary setup."

            "\nHugepages ARGUMENTS: *"
            "  2M, 1G\t\t\tHugepage size (2 MiB or 1 GiB)."
            "  [1-?]\t\t\t\tAmount of Hugepages (maximum amount is total memory subtracted by 4 GiB)."

            "\n  Example:"
            "    1G 16\t\t\t1 GiB hugepage * 16\t== 16 GiB allocated to hugepages."
            "    2M 8192\t\t\t2 MiB hugepage * 8912\t== 16 GiB allocated to hugepages."

            "\nMain setup OPTIONS: *"
            "  -m, --multiboot\t\tCreate multiple GRUB entries for a Multi VGA VFIO setup."
            "  -s, --static\t\t\tInstall a Single VGA VFIO setup."
            "  -u, --uninstall\t\tUndo an existing VFIO setup."

            "\n  Example:"
            "    -l -m\t\t\tParse against local database, then deploy a Multi VGA VFIO setup."
            "    -s -o\t\t\tParse against online database, then deploy a Static VFIO setup."
            "\nPost-setup OPTIONS:"
            "  -H, --hooks\t\tInstall recommended libvirt-hooks and services."
            "  -l, --looking-glass\tInstall LookingGlass.\t\t\tStream video (and audio) from Guest to Host over PCI bus using shared-memory device."
            "  -L, --audio-loopback\tInstall the audio loopback service.\tLoopback audio from Guest to Host (over Line-out to Line-in). *"
            "  -S, --scream\t\tInstall Scream.\t\t\t\tStream audio from Guest to Host over virtual LAN."
            "  -z, --zram-swap\tCreate compressed (~ 2:1) RAM swap.\tReduce chances of memory exhaustion for Host."
            "  --uninstall-extras\tUndo changes made by post-setup. *"

            "\nzram-swap ARGUMENTS:"
            "  force\t\t\tForce changes, even if zram-swap is allocated and in use. *"
            "  [fraction]\t\tSet the fraction of total available memory."

            "\n  Example (assume a Host with 32 GiB of RAM):"
            "    force 1/4\t\tCompress 8 GiB of RAM, to create 16 GiB of swap, with 16 GiB free."
            "\n* Options that skip *all* user prompts."
        )

        echo -e "${_OUTPUT[*]}"
        unset IFS
        return 0
    }

    # <summary> Set option for given argument. </summary>
    # <param name="1"> string: the option </param>
    function GetZramSwapOverride
    {
        case "$1" in
            "force" )
                _ZRAM_SWAP_OVERRIDE=true
                ;;

            * )
                return 1
                ;;
        esac

        return 0
    }

    # <summary> Set option for given argument. </summary>
    # <param name="1"> string: the option </param>
    function GetZramSwapSize
    {
        [ "$1" == "" ] || return 0

        case "$1" in
            *"/"* )
                ;;
            * )
                echo -e "$_PREFIX_FAIL Not a fraction."
                return 1
                ;;
        esac

        local -i _NUMERATOR=$( echo $1 | cut -d '/' -f1 )
        local -i _DENOMINATOR=$( echo $1 | cut -d '/' -f2 )

        if ! [[ "$_NUMERATOR" =~ '^[0-9]+$' ]] \
            || ! [ "$_DENOMINATOR" =~ '^[0-9]+$' ]; then
            echo -e "$_PREFIX_FAIL Not a fraction."
            return 1
        fi

        if [[ $_NUMERATOR -lt $_DENOMINATOR ]] || [[ $_DENOMINATOR -gt 1 ]]; then
            _ZRAM_SWAP_SET_FRACTION=true
            declare -g _ZRAM_SWAP_FRACTION="$1"
            return 0

        elif [[ $_DENOMINATOR -eq 0 ]]; then
            return 1

        else
             echo -e "$_PREFIX_FAIL Invalid fraction."
        fi

        return 1
    }

    # <summary> Sets the options. Exit early (Pass) if input is null. Else, exit early (Fail) if input is invalid. </summary>
    # <param name="@"> array: the input parameters </param>
    function SetOptions
    {
        for VAR_OPTION in "$@"; do
            [ "$VAR_OPTION" == "" ] && return 0
            GetOption "$VAR_OPTION" || return "$?"
        done

        return 0
    }
# </code>