#!/bin/bash/env bash

#
# Filename:       deploy-vfio
# Description:    Main executable. See README for details and usage.
# Author(s):      Alex Portell <github.com/portellam>
# Maintainer(s):  Alex Portell <github.com/portellam>
#

#
# TODO:
# - [ ] create dicts for each source files args.
# - [ ] create "high-level" execution here.
# - [ ] maintain readability such that the user may create his own "deploy-vfio".
# - [ ] pre-setup
#   - [ ] create src_isolcpu.
# - [ ] add repos
#   - [ ] "Audio Loopback"  "github.com/portellam/audio-loopback"
#   - [ ] "Scream"          "github.com/duncanthrax/scream"
#

#
# sources
#
  declare -g SCRIPT_DIR="/usr/local/bin/"
  declare -g SCRIPT_BIN_DIR="${SCRIPT_DIR}deploy-vfio.d/"

  source "${SCRIPT_BIN_DIR}src_print" "${0}"
  source "${SCRIPT_BIN_DIR}src_privileges"
  source "${SCRIPT_BIN_DIR}src_compatibility"
  source "${SCRIPT_BIN_DIR}src_isolcpu"
  source "${SCRIPT_BIN_DIR}src_hugepages"
  source "${SCRIPT_BIN_DIR}src_vfio_setup"
  source "${SCRIPT_BIN_DIR}src_network"
  source "${SCRIPT_BIN_DIR}src_auto_xorg"
  source "${SCRIPT_BIN_DIR}src_libvirt_hooks"
  source "${SCRIPT_BIN_DIR}src_looking_glass"
  source "${SCRIPT_BIN_DIR}src_scream"
  source "${SCRIPT_BIN_DIR}src_zram_swap"

#
# params
#
  declare -ir INT_MAX_FREE_MEMORY_KILOBYTES=$( \
    cat /proc/meminfo | grep --ignore-case MemTotal | \
    cut --delimiter ":" --fields 2 | awk 'END {print $1}' \
  )

  #
  # DESC: Compatibility checks
  #
    BOOL_COMPATIBILITY_SKIP=false

  #
  # DESC: Pre setup
  #
    BOOL_PRE_SETUP_SKIP=false

    declare -A DICT_HUGEPAGES_ARGS=(
      ["COUNT"]="",
      ["COUNT_SIZE_KILOBYTES"]="",
      ["MAX_COUNT_SIZE_KILOBYTES"]=""
      ["MAX_FREE_MEMORY_KILOBYTES"]="${INT_MAX_FREE_MEMORY_KILOBYTES}"
      ["SIZE"]="",
      ["SKIP"]=false,
    )

    declare -A DICT_ISOLCPU_ARGS=(
      ["SKIP"]=false,
      ["THREAD_SETS"]="",
    )

  #
  # DESC: Main setup
  #
    BOOL_SKIP_MAIN_SETUP=false

    declare -A DICT_IOMMU_ARGS=(
      ["IOMMU_GROUPS"]="",
      ["SELECT_ALL"]=true,
      ["SELECT_ALL_NON_VGA"]=false,
      ["SKIP"]=false,
      ["USE_DEFAULT_XML"]="",
      ["XML_FILE_NAME"]="",
    )

    declare -A DICT_VFIO_ARGS=(
      # TODO: validate in src_vfio_setup for CMDLINE args (ex: hugepages, isolcpu, devices)
      ["CUSTOM_CMDLINE_STRING"]="",
      ["HUGEPAGES_COUNT"]="",
      ["HUGEPAGES_SIZE"]="",
      ["IOMMU_GROUPS"]="",
      ["ISOLCPU_THREAD_SETS"]="",
      ["MULTI_BOOT_SETUP"]=true
      ["SKIP"]=false,
      ["STATIC_SETUP"]=false
    )

  #
  # DESC: Post setup
  #
    BOOL_SKIP_POST_SETUP=false

    declare -A DICT_AUTO_XORG_ARGS=(
      ["ARGS"]=""
      ["INSTALL"]=false,
      ["SKIP"]=false,
      ["UNINSTALL"]=false,
      ["UPDATE"]=false,
    )

    declare -A DICT_LIBVIRT_HOOKS_ARGS=(
      ["INSTALL"]=false,
      ["SKIP"]=false,
      ["UNINSTALL"]=false,
      ["UPDATE"]=false,
    )

    declare -A DICT_LOOKING_GLASS_ARGS=(
      ["BUFFER_SIZE"]="",
      ["INSTALL"]=false,
      ["SKIP"]=false,
      ["UPDATE"]=false,
      ["USE_DEFAULTS"]=true,
    )

    declare -A DICT_ZRAM_SWAP_ARGS=(
      ["FORCE_RESTART"]=false,
      ["HUGEPAGES_MAX_COUNT_SIZE_KILOBYTES"]="",
      ["INSTALL"]=false,
      ["MODIFY"]=false,
      ["RESERVED_MEMORY_FRACTION"]="",
      ["RESTART"]=false,
      ["SKIP"]=false,
      ["UPDATE"]=false,
      ["USE_CALCULATION"]=false,
      ["USE_DEFAULTS"]=true,
    )

#
# logic
#
  #
  # DESC:   Main function.
  # $*:     the command line arguments as an array.
  # RETURN: If script executes successfully, return 0.
  #         If not, return 1.
  #
    function main
    {
      # TODO: develop!
      return 1

      if ! src_privileges_is_user_superuser \
        || ! is_system_supported; then
        return 1
      fi

      # TODO: add pre setup.
      print_and_log_work "Executing pre setup..."

      # if ! hugepages \
      #   || ! isolcpu; then
      #   print_and_log_fail "Pre setup failed."
      #   return 1
      # fi

      if ! hugepages; then
        print_and_log_fail "Pre setup failed."
        return 1
      fi

      print_and_log_pass "Pre setup complete."
      # print_and_log_work "Executing main setup..."

      # TODO: add main setup.
      # if ! iommu \
      #   || ! vfio_setup; then
      #   print_and_log_fail "Main setup failed."
      #   return 1
      # fi

      # print_and_log_pass "Main setup complete."
      print_and_log_work "Executing post setup..."

      # TODO: add remaining.
      # if ! auto_xorg \
      #   || ! libvirt_hooks \
      #   || ! looking_glass \
      #   || ! scream \
      #   || ! zram_swap; then
      if ! auto_xorg \
        || ! libvirt_hooks \
        || ! zram_swap; then
        print_and_log_fail "Post setup failed."
        return 1
      fi

      print_and_log_pass "Post setup complete."
      print_and_log_pass
    }

  #
  # DESC:   Parse arguments.
  # $*:     the command line arguments as an array.
  # RETURN: If all arguments are valid, or none are passed, return 0
  #         If one or more arguments are not valid, return 1.
  #         If an exception occurs, return 2.
  #
    function parse_args
    {
      # TODO: develop!
      return 1
    }

  #
  # DESC: Pre setup
  #
    function hugepages
    {
      if ! src_hugepages_main \
          "${DICT_HUGEPAGES_ARGS["SKIP"]}" \
          "${DICT_HUGEPAGES_ARGS["SIZE"]}" \
          "DICT_HUGEPAGES_ARGS[\"COUNT_SIZE_KILOBYTES\"]" \
          "DICT_HUGEPAGES_ARGS[\"COUNT\"]" \
          "${DICT_HUGEPAGES_ARGS["MAX_FREE_MEMORY_KILOBYTES"]}"
          "DICT_HUGEPAGES_ARGS[\"MAX_COUNT_SIZE_KILOBYTES\"]"; then
        return 1
      fi

      return 0
    }

  #
  # DESC: Main setup
  #
    function iommu
    {
      # if ! src_iommu; then
      #   return 1
      # fi

      return 0
    }

    function vfio_setup
    {
      DICT_VFIO_ARGS["HUGEPAGES_COUNT"]="${DICT_HUGEPAGES_ARGS["COUNT"]}"
      DICT_VFIO_ARGS["HUGEPAGES_SIZE"]="${DICT_HUGEPAGES_ARGS["SIZE"]}"
      DICT_VFIO_ARGS["ISOLCPU_THREAD_SETS"]="${DICT_ISOLCPU_ARGS["THREAD_SETS"]}"
      DICT_VFIO_ARGS["IOMMU_GROUPS"]="${DICT_IOMMU_ARGS["IOMMU_GROUPS"]}"

      # if ! src_vfio_setup; then
      #   return 1
      # fi

      return 0
    }

  #
  # DESC: Post setup
  #
    function auto_xorg
    {
      if ! src_auto_xorg_main \
          "${DICT_AUTO_XORG_ARGS["SKIP"]}" \
          "${DICT_AUTO_XORG_ARGS["INSTALL"]}" \
          "${DICT_AUTO_XORG_ARGS["UNINSTALL"]}" \
          "${DICT_AUTO_XORG_ARGS["UPDATE"]}" \
          "DICT_AUTO_XORG_ARGS[\"ARGS\"]"; then
        return 1
      fi

      return 0
    }

    function libvirt_hooks
    {
      if ! src_libvirt_hooks_main \
          "${DICT_LIBVIRT_HOOKS_ARGS["SKIP"]}" \
          "${DICT_LIBVIRT_HOOKS_ARGS["INSTALL"]}" \
          "${DICT_LIBVIRT_HOOKS_ARGS["UNINSTALL"]}" \
          "${DICT_LIBVIRT_HOOKS_ARGS["UPDATE"]}"; then
        return 1
      fi

      return 0
    }

    function zram_swap
    {
      DICT_ZRAM_SWAP_ARGS["HUGEPAGES_MEMORY_COUNT_BYTES"]=""

      if ! src_zram_swap_main \
          "${DICT_ZRAM_SWAP_ARGS["SKIP"]}" \
          "${DICT_ZRAM_SWAP_ARGS["MODIFY"]}" \
          "${DICT_ZRAM_SWAP_ARGS["INSTALL"]}" \
          "${DICT_ZRAM_SWAP_ARGS["UNINSTALL"]}" \
          "${DICT_ZRAM_SWAP_ARGS["UPDATE"]}" \
          "${DICT_ZRAM_SWAP_ARGS["RESTART"]}" \
          "${DICT_ZRAM_SWAP_ARGS["USE_CALCULATION"]}" \
          "${DICT_ZRAM_SWAP_ARGS["USE_DEFAULTS"]}" \
          "${DICT_ZRAM_SWAP_ARGS["RESERVED_MEMORY_FRACTION"]}" \
          "${DICT_ZRAM_SWAP_ARGS["HUGEPAGES_MEMORY_COUNT_BYTES"]}"; then
        return 1
      fi

      return 0
    }

#
# main logic
#
  parse_args "$@"
  main