#!/bin/bash

#
# Filename:         /etc/libvirt/hooks/qemu
# Description:      Prevent system sleep while libvirt domain is running.
# URL(s):           https://web.archive.org/web/20220808031554/https://old.reddit.com/r/VFIO/comments/8ypedp/for_anyone_getting_issues_with_their_guest_when/
# Author(s):        sm-Fifteen <reddit.com/u/sm-Fifteen>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

OBJECT="$1"
OPERATION="$2"
SUBOPERATION="$3"
EXTRA_ARG="$4"

case "$OPERATION" in
        "prepare")
                systemctl start libvirt-nosleep@"$OBJECT"
                ;;
        "release")
                systemctl stop libvirt-nosleep@"$OBJECT"
                ;;
esac