#!/bin/bash

#
# Filename:         /etc/libvirt/hooks/nosleep
# Description:      Prevent system sleep while libvirt domain is running.
# URL(s):           https://web.archive.org/web/20220808031554/https://old.reddit.com/r/VFIO/comments/8ypedp/for_anyone_getting_issues_with_their_guest_when/
# Author(s):        sm-Fifteen <reddit.com/u/sm-Fifteen>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

HOOK_NAME="nosleep"
PREFIX_ERROR="An error occurred:"
PREFIX_PROMPT="libvirt-qemu ${HOOK_NAME}:"
DOMAIN_NAME="${1}"
OPERATION="${2}"

function StartNosleepService
{
    if ! systemctl start libvirt-nosleep@"${DOMAIN_NAME}" &> /dev/null; then
        echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to start Nosleep service for Libvirt domain '${DOMAIN_NAME}'." >&2
        return 1
    fi

    echo "${PREFIX_PROMPT} Started Nosleep service for Libvirt domain '${DOMAIN_NAME}'."
    return 0
}

function StopNosleepService
{
    if ! systemctl stop libvirt-nosleep@"${DOMAIN_NAME}" &> /dev/null; then
        echo "${PREFIX_PROMPT} ${PREFIX_ERROR} Failed to stop Nosleep service for Libvirt domain '${DOMAIN_NAME}'." >&2
        return 1
    fi

    echo "${PREFIX_PROMPT} Stopped Nosleep service for Libvirt domain '${DOMAIN_NAME}'."
    return 0
}

case "${OPERATION}" in
    "prepare")
        StartNosleepService ;;
    "release")
        StopNosleepService ;;
esac