#!/bin/bash

#
# Filename:         /etc/libvirt/hooks/nosleep
# Description:      Prevent system sleep while libvirt domain is running.
# URL(s):           https://web.archive.org/web/20220808031554/https://old.reddit.com/r/VFIO/comments/8ypedp/for_anyone_getting_issues_with_their_guest_when/
# Author(s):        sm-Fifteen <reddit.com/u/sm-Fifteen>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

_HOOK_NAME="nosleep"
_PREFIX_PROMPT="libvirt-qemu $_HOOK_NAME:"
_DOMAIN_NAME="$1"
_OPERATION="$2"

function StartNosleepService
{
    if ! systemctl start libvirt-nosleep@"$_DOMAIN_NAME" &> /dev/null; then
        echo "$_PREFIX_PROMPT An error occured: Failed to start Nosleep service for Libvirt domain '$_DOMAIN_NAME'." >&2
        return 1
    fi

    echo "$_PREFIX_PROMPT Started Nosleep service for Libvirt domain '$_DOMAIN_NAME'."
    return 0
}

function StopNosleepService
{
    if ! systemctl stop libvirt-nosleep@"$_DOMAIN_NAME" &> /dev/null; then
        echo "$_PREFIX_PROMPT An error occured: Failed to stop Nosleep service for Libvirt domain '$_DOMAIN_NAME'." >&2
        return 1
    fi

    echo "$_PREFIX_PROMPT Stopped Nosleep service for Libvirt domain '$_DOMAIN_NAME'."
    return 0
}

case "$_OPERATION" in
    "prepare")
        StartNosleepService ;;
    "release")
        StopNosleepService ;;
esac