#!/bin/bash

#
# Filename:         /etc/libvirt/hooks/nosleep
# Description:      Prevent system sleep while libvirt domain is running.
# URL(s):           https://web.archive.org/web/20220808031554/https://old.reddit.com/r/VFIO/comments/8ypedp/for_anyone_getting_issues_with_their_guest_when/
# Author(s):        sm-Fifteen <reddit.com/u/sm-Fifteen>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

_DOMAIN_NAME="$1"
_OPERATION="$2"

case "$_OPERATION" in
    "prepare")
        systemctl start libvirt-nosleep@"$_DOMAIN_NAME" ;;
    "release")
        systemctl stop libvirt-nosleep@"$_DOMAIN_NAME" ;;
esac