#!/bin/bash

#
# Filename:         /etc/libvirt/hooks/qemu
# Author(s):        Alex Portell <github.com/portellam>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

# <remarks> Usage </remarks>