#!/bin/bash

#
# Filename:         /etc/libvirt/hooks/qemu
# Author(s):        Alex Portell <github.com/portellam>
# Maintainer(s):    Alex Portell <github.com/portellam>
#

# <remarks>If a script exits with an error, exit Libvirt.</remarks>
set -e