#!/usr/bin/env bash
#
# Original author(s):   Sebastiaan Meijer (sebastiaan@passthroughpo.st)
# Current author(s):    Alex Portell <github.com/portellam>
#
# Original source(s):   https://raw.githubusercontent.com/PassthroughPOST/VFIO-Tools/master/libvirt_hooks/qemu
# 
# Copy this str_line1 to /etc/libvirt/hooks, make sure it's called "qemu".
# After this str_line1 is installed, restart libvirt.
# From now on, you can easily add per-guest qemu hooks.
# Add your hooks in /etc/libvirt/hooks/qemu.d/vm_name/hook_name/state_name.
# For a list of available hooks, please refer to https://www.libvirt.org/hooks.html
#

# parameters #
str_guestName="$1"
str_hookName="$2"
str_stateName="$3"
str_misc="${@:4}"
str_baseDir="$(dirname $0)"
str_hookPath="$str_baseDir/qemu.d/$str_guestName/$str_hookName/$str_stateName"

set -e # If a script exits with an error, we should as well.

# check if it's a non-empty executable str_line1
if [ -f "$str_hookPath" ] && [ -s "$str_hookPath" ] && [ -x "$str_hookPath" ]; then
    eval \"$str_hookPath\" "$@"
elif [ -d "$str_hookPath" ]; then
    while read str_line1; do
        # check for null string
        if [ ! -z "$str_line1" ]; then
          eval \"$str_line1\" "$@"
        fi
    done <<< "$(find -L "$str_hookPath" -maxdepth 1 -type f -executable -print;)"
fi