#!/usr/bin/env bash
#
# Original author(s):   reddit.com/u/sm-Fifteen
# Current author(s):    Alex Portell <github.com/portellam>
#
# Original source(s):   https://wiki.archlinux.org/index.php?title=PCI_passthrough_via_OVMF#Host_lockup_if_guest_is_left_running_during_sleep
# 
# Create nosleep service for each active domain (wake VM).
#

# parameters #
str_object="$1"
str_operation="$2"
str_subOperation="$3"
str_extraArg="$4"

case "$str_operation" in
        "prepare")
                systemctl start libvirt-nosleep@"$str_object"
                ;;
        "release")
                systemctl stop libvirt-nosleep@"$str_object"
                ;;
esac