#!/bin/sh

#
# Source:               https://wiki.archlinux.org/index.php?title=PCI_passthrough_via_OVMF#Host_lockup_if_guest_is_left_running_during_sleep
# Original author(s):   reddit.com/u/sm-Fifteen
# Current author(s):    Alex Portell <github.com/portellam>
#
# DESCRIPTION: create nosleep service for each active domain (wake VM).
#

# parameters #
OBJECT="$1"
OPERATION="$2"
SUBOPERATION="$3"
EXTRA_ARG="$4"

case "$OPERATION" in
        "prepare")
                systemctl start libvirt-nosleep@"$OBJECT"
                ;;
        "release")
                systemctl stop libvirt-nosleep@"$OBJECT"
                ;;
esac